### ISSUE TITLE
Tabs are not clearly links - Add appropriate styling

### ISSUE THREAD

**Issue by elaewin** [agrampa/Portfolio#15]
It's a bit confusing, looking at your site, because I can't tell that your Home, About, and Online tabs are actually "links" to new content. 

You always want to give your user some kind of visual indication that part of your site is interactive. Look at the links you have below your tabs: when you mouse over them, they change color, and the cursor on the changes to a pointer finger. Those two things are a convention that tell users that those are links. You want the same kind of interactive response for your navigation tabs.

**Comment by agrampa** [comment]
fixed
