### ISSUE TITLE
Github token is visible!

### ISSUE THREAD

**Issue by elaewin** [agrampa/Portfolio#31]
Update your .gitignore to include this. 

Then ACP, and run the following commands in your terminal:
```
git rm -r --cached .
git add .
git commit -m "gitignore is updated."
```

**Comment by agrampa** [comment]
fixed

**Comment by agrampa** [comment]
I fixed this in Atom, ACP, merged, resubmitted, then remembered to check this issue. I did these commands just now and it says my class-12 branch is already up to date.
