### ISSUE TITLE
Apply updated .gitignore to the project

### ISSUE THREAD

**Issue by elaewin** [agrampa/Portfolio#34]
Your .gitignore file is updated, but it doesn't have an automatic retroactive effect on your repo. To make sure the updated version is omitting the right files, make sure you've committed any changes and run the following commands in your terminal (master branch):
```
    git rm -r --cached .
    git add .
    git commit -m "updated .gitignore now working"
```
Once you do that, check to make sure the excluded files aren't in the repo any more.

**Comment by agrampa** [comment]
i think it is working now
